version: "3"

vars:
  docker_run: docker compose run --rm terraform
  log_level: info
  env: xxxx
  module: xxxx
  auto_approve: "false"

tasks:
  # ==============================================================================
  # Information
  # ==============================================================================

  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # ==============================================================================
  # Docker Environment
  # ==============================================================================

  shell:
    desc: Open bash shell in Docker container
    cmds:
      - "{{.docker_run}} bash"

  # ==============================================================================
  # Format
  # ==============================================================================

  format:
    desc: Format all .tf and .hcl files
    cmds:
      - >
        {{.docker_run}} bash -c
        'terraform fmt -recursive /app/terraform &&
        terragrunt hcl fmt /app/terraform'

  # ==============================================================================
  # Lint
  # ==============================================================================

  lint-init:
    desc: Initialize tflint plugins
    cmds:
      - >
        {{.docker_run}} bash -c
        'tflint --init --config /app/.tflint.hcl'

  lint:
    desc: Run tflint on all resources and modules recursively
    deps: [lint-init]
    cmds:
      - >
        {{.docker_run}} bash -c
        'tflint --config /app/.tflint.hcl --chdir /app/terraform --recursive'

  # ==============================================================================
  # Terragrunt Commands
  # ==============================================================================

  init:
    desc: Initialize Terragrunt
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}}/{{.module}} &&
        terragrunt
        --log-level {{.log_level}}
        --non-interactive
        init'

  plan:
    desc: Plan Terragrunt
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}}/{{.module}} &&
        terragrunt
        --log-level {{.log_level}}
        plan'

  apply:
    desc: Apply Terragrunt (use auto_approve=true for --auto-approve)
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}}/{{.module}} &&
        terragrunt
        --log-level {{.log_level}}
        apply{{if eq .auto_approve "true"}} --auto-approve{{end}}'

  destroy:
    desc: Destroy Terragrunt (use auto_approve=true for --auto-approve)
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}}/{{.module}} &&
        terragrunt
        --log-level {{.log_level}}
        destroy{{if eq .auto_approve "true"}} --auto-approve{{end}}'

  validate:
    desc: Validate Terraform configuration
    deps: [init]
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}}/{{.module}} &&
        terragrunt
        --log-level {{.log_level}}
        validate'

  # ==============================================================================
  # Advanced Commands
  # ==============================================================================

  init-all:
    desc: Initialize all modules in environment
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}} &&
        terragrunt
        --log-level {{.log_level}}
        --non-interactive
        run --all init'

  plan-all:
    desc: Plan all modules in environment
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}} &&
        terragrunt
        --log-level {{.log_level}}
        run --all plan'

  apply-all:
    desc: Apply all modules in environment (use auto_approve=true for --non-interactive)
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}} &&
        terragrunt
        --log-level {{.log_level}}{{if eq .auto_approve "true"}}
        --non-interactive{{end}}
        run --all apply'

  destroy-all:
    desc: Destroy all modules in environment (use auto_approve=true for --non-interactive)
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}} &&
        terragrunt
        --log-level {{.log_level}}{{if eq .auto_approve "true"}}
        --non-interactive{{end}}
        run --all destroy'

  # ==============================================================================
  # State Management
  # ==============================================================================

  state-list:
    desc: List resources in Terraform state for current module
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}}/{{.module}} &&
        terragrunt
        --log-level {{.log_level}}
        state list'

  state-list-all:
    desc: List resources in Terraform state for all modules
    cmds:
      - >
        {{.docker_run}} bash -c
        'cd /app/terraform/environments/{{.env}} &&
        terragrunt
        --log-level {{.log_level}}
        run --all state list'
